### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for ViaPotions

### ISSUE THREAD

**Issue by mibby** [2lstudios-mc/ViaPotions#12]
Paper 1.19 (Purpur 1668)
ProtocolLib dev 569
ViaVersion dev 617
ViaBackwards dev 271
ViaRewind dev 127
ViaRewind Legacy Support 19
ViaPotions dev 0.0.4

```
[04:27:45] [Server thread/WARN]: [ProtocolLib] Loaded class dev._2lstudios.viapotions.listeners.SpawnEntityListener from ViaPotions v0.0.4 which is not a depend or softdepend of this plugin.
[04:27:45] [Server thread/ERROR]: [ViaPotions] Unhandled exception occurred in onPacketSending(PacketEvent) for ViaPotions
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 6, Size: 5)
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:?]
	at dev._2lstudios.viapotions.listeners.SpawnEntityListener.onPacketSending(SpawnEntityListener.java:33) ~[ViaPotions.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
	at net.minecraft.network.Connection.processQueue(Connection.java:531) ~[?:?]
	at net.minecraft.network.Connection.flushQueue(Connection.java:494) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:402) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2150) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2136) ~[?:?]
	at me.filoghost.holographicdisplays.nms.v1_19_R1.VersionNMSPacket.sendTo(VersionNMSPacket.java:17) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.nms.common.IndividualTextPacketGroupImpl$IndividualTextPacketGroup2.sendTo(IndividualTextPacketGroupImpl.java:46) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.Viewer.sendIndividualPackets(Viewer.java:35) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.TextLineViewer.sendTextPackets(TextLineViewer.java:29) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.TextLineTracker.lambda$sendSpawnPackets$0(TextLineTracker.java:90) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.MutableViewers.forEach(MutableViewers.java:32) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.TextLineTracker.sendSpawnPackets(TextLineTracker.java:90) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.LineTracker.modifyViewersAndSendPackets(LineTracker.java:132) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.LineTracker.update(LineTracker.java:86) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.LineTrackerManager.update(LineTrackerManager.java:66) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tick.TickingTask.run(TickingTask.java:69) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1668]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:27:45] [Netty Epoll Server IO #1/ERROR]: Packet encoding of packet ID 48 threw (skippable? true)
java.lang.NullPointerException: Cannot invoke "java.time.Instant.toEpochMilli()" because "instant" is null
	at net.minecraft.network.FriendlyByteBuf.writeInstant(FriendlyByteBuf.java:697) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.write(ClientboundPlayerChatPacket.java:49) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[purpur-1.19.jar:git-Purpur-1668]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93) ~[ViaVersion-4.3.2-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71) ~[ViaVersion-4.3.2-SNAPSHOT.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at de.themoep.ShowItem.InternalChatManager$1.write(InternalChatManager.java:60) ~[ShowItem.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at com.interactiveboard.utility.nms.map.MapPacket_1_19_R1$1.write(MapPacket_1_19_R1.java:41) ~[InteractiveBoard.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:91) ~[TAB v3.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at xuan.cat.fartherviewdistance.code.branch.v19.Branch_19_Minecraft$1.write(Branch_19_Minecraft.java:109) ~[FartherViewDistance-9.5.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:463) ~[?:?]
	at net.minecraft.network.Connection.lambda$writePacket$11(Connection.java:437) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:27:45] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutSpawnEntity@48fad40[
    c=628
    d=aa13f810-3f4e-47fd-8a0e-91820dded81c
    e=entity.minecraft.armor_stand
    f=-26.5
    g=55.730000000000004
    h=-13.5
    i=0
    j=0
    k=0
    l=0
    m=0
    n=0
    o=0
  ]

[04:27:45] [Server thread/ERROR]: [ViaPotions] Unhandled exception occurred in onPacketSending(PacketEvent) for ViaPotions
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 6, Size: 5)
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:?]
	at dev._2lstudios.viapotions.listeners.SpawnEntityListener.onPacketSending(SpawnEntityListener.java:33) ~[ViaPotions.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:436) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2150) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2136) ~[?:?]
	at me.filoghost.holographicdisplays.nms.v1_19_R1.VersionNMSPacket.sendTo(VersionNMSPacket.java:17) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.nms.common.IndividualTextPacketGroupImpl$IndividualTextPacketGroup2.sendTo(IndividualTextPacketGroupImpl.java:46) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.Viewer.sendIndividualPackets(Viewer.java:35) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.TextLineViewer.sendTextPackets(TextLineViewer.java:29) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.TextLineTracker.lambda$sendSpawnPackets$0(TextLineTracker.java:90) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.MutableViewers.forEach(MutableViewers.java:32) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.TextLineTracker.sendSpawnPackets(TextLineTracker.java:90) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.LineTracker.modifyViewersAndSendPackets(LineTracker.java:132) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.LineTracker.update(LineTracker.java:86) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tracking.LineTrackerManager.update(LineTrackerManager.java:66) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at me.filoghost.holographicdisplays.core.tick.TickingTask.run(TickingTask.java:69) ~[HolographicDisplays-3.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1668]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1668]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:27:45] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutSpawnEntity@6ca86eb7[
    c=629
    d=c30a7475-8f64-449d-bf73-afc5eafd8e9d
    e=entity.minecraft.armor_stand
    f=-26.5
    g=55.480000000000004
    h=-13.5
    i=0
    j=0
    k=0
    l=0
    m=0
    n=0
    o=0
  ]

```

**Comment by DrkMatr1984** [comment]
Same
Similar Setup also.

**Comment by LoboMetalurgico** [comment]
Same here (1.19.2), this plugin needs an update to become compatible with newer minecraft versions.

**Comment by linsaftw** [comment]
Packet data changed and ViaPotions has to be adapted to this change.
